#
# (https://wiki.hyprland.org/Configuring/Environment-variables/)
#

# Hardware acceleration on NVIDIA GPUs
# (https://wiki.archlinux.org/title/Hardware_video_acceleration)
env = LIBVA_DRIVER_NAME,nvidia

# (https://wiki.archlinux.org/title/Wayland#Requirements)
# WARN: can crash hyprland
env = GBM_BACKEND,nvidia-drm
# To force GBM as a backend
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

env = __VK_LAYER_NV_optimus,NVIDIA_only
env = NVD_BACKEND,direct

# Screnshots directory
env = XDG_SCREENSHOTS_DIR, ~/Obrázky/Snímky\ obrazovky/

# Windows
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = QT_QPA_PLATFORMTHEME,gtk3
