# See https://wiki.hyprland.org/Configuring/Monitors/

# Default
#monitor = , preferred, auto, auto

# In my case I configured my monitor on DisplayPort-2
# to have resolution 3440x1440, 165 FPS and 10 bit color depth to support HDR.
monitor = DP-2, 3440x1440@165, 0x0, 1, bitdepth, 10, cm, srgb
monitor = DP-3, 1920x1080@75, 3440x-450, 1, transform, 3
