# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Specific tweaks for Albert launcher.
windowrule = move 40.7% 30%, title:(^Albert$) # Position
windowrule = stayfocused, title:(^Albert$) # Focus
windowrule = float, title:(^Settings — Albert$) # Floating settings

# Specific tweaks for Gitify
windowrule = stayfocused, class:(^gitify$) # Focus
windowrule = noinitialfocus, class:(^gitify$) # No initial focus
windowrule = move 80% 5%, class:(^gitify$) # Move

# Specific tweaks for Mega
windowrule = float, class:(MEGAsync) # Float

# Floating windows
windowrule = float, class:(Electron)
windowrule = float, class:(org.telegram.desktop)
windowrule = float, class:(org.gnome.Calendar)

# Pinned windows
windowrule = pin, class:(org.telegram.desktop)
windowrule = pin, class:(geary)

# -- Fix odd behaviors in IntelliJ IDEs --
#! Disable window flicker when autocomplete or tooltips appear
windowrule = nofocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1
windowrule = noinitialfocus, class:(jetbrains-)(.*), floating:1
