# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Specific tweaks for Albert launcher.
windowrulev2 = move 40.7% 30%, title:(^Albert$) # Position
windowrulev2 = stayfocused, title:(^Albert$) # Focus
windowrulev2 = float, title:(^Settings — Albert$) # Floating settings

# Specific tweaks for Gitify
windowrulev2 = stayfocused, class:(^gitify$) # Focus
windowrulev2 = noinitialfocus, class:(^gitify$) # No initial focus
windowrulev2 = move 80% 5%, class:(^gitify$) # Move

# Floating windows
windowrulev2 = float, class:(Electron)
windowrulev2 = float, class:(org.telegram.desktop)
windowrulev2 = float, class:(org.gnome.Calendar)

# Pinned windows
windowrulev2 = pin, class:(org.telegram.desktop)
windowrulev2 = pin, class:(geary)

# -- Fix odd behaviors in IntelliJ IDEs --
#! Disable window flicker when autocomplete or tooltips appear
windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1
windowrulev2 = noinitialfocus, class:(jetbrains-)(.*), floating:1
