--hwdec=yes
--no-config
--vo=gpu-next
--target-colorspace-hint
--target-colorspace-hint-mode=source
--gpu-context=waylandvk
--gpu-api=vulkan
--hdr-compute-peak=no
--framedrop=no
--sub-file-paths=sub:subtitles:Subs
--sub-auto=all
